# Generated by Django 2.1.5 on 2019-02-03 14:28

from django.db import migrations, models
import spots.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default=None, max_length=255)),
                ("name_sub", models.CharField(default=None, max_length=255)),
                ("branch", models.CharField(default=None, max_length=255)),
                ("address", models.CharField(default=None, max_length=255)),
                ("building", models.CharField(default=None, max_length=255)),
                ("phone", models.CharField(default=None, max_length=255)),
                ("description", models.TextField(default=None)),
                (
                    "business_status",
                    models.CharField(choices=[(spots.models.BusinessStatus("Closed"), "Closed")], max_length=255),
                ),
                ("business_status_confirm_time", models.DateTimeField()),
            ],
        )
    ]
