# Generated by Django 2.1.5 on 2019-02-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spots", "0005_spot_business_hour")]

    operations = [
        migrations.AddField(model_name="spot", name="published_time", field=models.DateTimeField(blank=True, null=True))
    ]
