# Generated by Django 2.1.5 on 2019-02-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spots", "0006_spot_published_time")]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=8, verbose_name="緯度"),
        ),
        migrations.AddField(
            model_name="spot",
            name="lng",
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, verbose_name="経度"),
        ),
    ]
