# Generated by Django 2.1.5 on 2019-02-26 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_auto_20190224_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='順番')),
                ('url', models.TextField(verbose_name='URL')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.Spot', verbose_name='紐づくスポット')),
            ],
        ),
    ]
