version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - .:/var/www/docker_django
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_docker_django
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
    - "23306:3306"
  web:
    build: .
    command: sh -c "./wait-for-it.sh db:3306; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/var/www/docker_django
    ports:
    - "8080:8000"
    depends_on:
    - db
